### PR TITLE
Expo Go: Fix mobile issue

### PR DESCRIPTION
**Pull request by Stronkness**
## Checklist
- [X] Have you remembered to run the `test_actions.sh` script?
- [X] Have you rebased the branch on the latest main?
- [X] Have you tested the change locally?

Solves #267 

As stated before Expo Go wouldn't co-work with us to test our app on the phone. This is fixed now as Expo Go updated their app to support SDK 48. This means that the nexpo-app has been updated to SDK 48 (Expo 48, latest version) and updated some packages (where some was not automatically updated).

However to make the backend (nexpo-backend-nova) to actually work on Expo Go you need to change the routing of information as your phone doesn't understand what localhost is. To test the update do the following:
- Be on the same Wi-Fi on phone and computer.
- Fetch the IP address of the network
- Go into nexpo-app and the file called `app.config.ts` and change `backendUrl` to `http://YOUR-IP-ADDRESS:5000/api`
- Go into the nexpo-backend-nova directory
- Change in `launchSettings.json` the `applicationUrl` to `http://YOUR-IP-ADDRESS:5000`
- Change in `appsettings.Development.json` the `Issuer, Audience & BaseUrl` variables where you switch out `localhost` to `YOUR-IP-ADDRESS`. Note that `BaseUrl` need the `:5000` port in order to work

The SDK 48 is tested locally on the web and works well. Currently for some reason when you are logged into the app after doing the steps above the app crashes when accessing the profile. Something to look into later.

Please tell me if the profile page when logged in doesn't crash for you. If it does not crash please state your phones operating system.

🚨 The following packages were not updated. You should check the READMEs for those repositories to determine what version is compatible with your new set of packages:
@react-native-community/masked-view, @react-navigation/bottom-tabs, @react-navigation/native, @react-navigation/stack, date-fns, fbjs, react-native-blob-util, react-native-dropdown-picker, react-native-image-zoom-viewer, react-native-keyboard-aware-scroll-view, react-native-qrcode-svg, react-native-tab-view, react-native-toast-message, sharp-cli, type-check, webpack-dev-server, @types/react-native, babel-plugin-module-resolver

### CODE REVIEW

**Comment by Stronkness** [comment]
Apparently the typecheck error is not fixed as the dependencies are updated in the data structures (SDK 48) the current code complains a bit, will fix soon

**Comment by Stronkness** [comment]
Has anyone tested this yet? I want atleast one Android and one iPhone user to test this at home

**Comment by emil-ronkainen** [comment]
I cannot seem to get the backend running when using the IP-address instead of localhost. It returns the following stacktrace

```
Unhandled exception. System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
```

Any ideas on how to fix this?

**Comment by Stronkness** [comment]
I tested with 192.168..... address, have you tried with 127.0.0.1?

**Comment by emil-ronkainen** [comment]
127.0.0.1 seems to resolve the backend error! However, I still get a socket timeout exception when attempting to scan the qr-code with my Android. Using 192.168... on the frontend side (app.config.ts)

**Comment by AlexanderHansson4225** [comment]
If you havent already:
1. dubbelcheck that port 5000 and 5432 isnt somehow used by another application.
2. Dubbelcheck that the ip and more importantly the port the backend uses matches the one the frontend uses (if you have changed that). It is in the appSettings.decelopment.json file.

 Those 2 times are the only times ive seen that error

**Comment by Stronkness** [comment]
> 127.0.0.1 seems to resolve the backend error! However, I still get a socket timeout exception when attempting to scan the qr-code with my Android. Using 192.168... on the frontend side (app.config.ts)

If I'm not mistaken you must also use the 127 address on the frontend for it to work

**Comment by S1monG** [comment]
Opening the app on mobile with expo go works fine for me (ios). However the app does not seem to work like intended. In the companies tab and events tab it's stuck on loading screen and it's also stuck when I try to login. I keep getting this warning: `Possible Unhandled Promise Rejection`. Anyone else with a similar error?

**Comment by Sepehr-trp** [comment]
I tried both with changing localhost to 127.0.0.1 and my actual IP but Expo Go on my iphone can't launch the app. I see two 'applicationUrl' in launchSettings.json (the other one under 'iisSettings'), if changing that can be important at all.

**Comment by Stronkness** [comment]
> Opening the app on mobile with expo go works fine for me (ios). However the app does not seem to work like intended. In the companies tab and events tab it's stuck on loading screen and it's also stuck when I try to login. I keep getting this warning: `Possible Unhandled Promise Rejection`. Anyone else with a similar error?

I recognize this error, i simply restarted the app and it worked, also checked that you edited all addresses correctly

**Comment by Stronkness** [comment]
> I tried both with changing localhost to 127.0.0.1 and my actual IP but Expo Go on my iphone can't launch the app. I see two 'applicationUrl' in launchSettings.json (the other one under 'iisSettings'), if changing that can be important at all.

Have you changed every address element as stated in the  PR description? Because it should work otherwise

**Comment by S1monG** [comment]
> I tried both with changing localhost to 127.0.0.1 and my actual IP but Expo Go on my iphone can't launch the app. I see two 'applicationUrl' in launchSettings.json (the other one under 'iisSettings'), if changing that can be important at all.

Yes, you need to change both applicationUrl's. My error was because I only changed the first one. It works for me now :)

**Comment by Stronkness** [comment]
Do you have an iphone or android? @S1monG 
Also, when logged in and you go into the profile page, does the app crash?

**Comment by S1monG** [comment]
> Do you have an iphone or android? @S1monG Also, when logged in and you go into the profile page, does the app crash?

Im running it on an Iphone and the app doesn't crash it's just a little buggy on the profile page. I have to manually reload when logging in to update the view. I suspect it is because the way we reload the app with `window.location.reload()` doesn't work on mobile? Loggin in as admin worked fine but when I try to log in as student the profilepage doesn't load correcly. It's also a little slow in general but I guess that's expected.

**Comment by Stronkness** [comment]
Amazing! Yes the app is a bit slow using Expo Go. We should investigate further about the reload

**Comment by Stronkness** [comment]
Could you try experimenting with reload? @S1monG

**Comment by S1monG** [comment]
> Could you try experimenting with reload? @S1monG

Sure

**Comment by Stronkness** [comment]
I would like one more to confirm that it works before i merge

**Comment by Stronkness** [comment]
Could you try it out tonight ? @AlexanderHansson4225

**Comment by Sepehr-trp** [comment]
I made all changes but still not able to launch the app on my phone 😢 Tried on my mobile network also.

**Comment by AlexanderHansson4225** [comment]
> Could you try it out tonight ? @AlexanderHansson4225

It works for me, however it only works using the 192.x.z.y ip (so not the 127.0.0.1)

**Pull request merged**
