### PR TITLE
305 admin should be able to change roles on users

### LINKED ISSUE #305: Admin should be able to change roles on users
An admin should be able to change the role of users. This could be done in the admin tab.

### PR DESCRIPTION
**Pull request by S1monG**
## Checklist
- [x] Have you remembered to run the `test_actions.sh` script?
- [x] Have you rebased the branch on the latest main?
- [x] Have you tested the change locally?

This pr contains two main changes to the admin tab:
 - A dropdown item picker is added to pick committes to send a mass message to.
 - A way for admins to change the role of any user.

NOTE:
The api calls to backend is not yet in place. I will have to work with the backend team to get this in place. 
The style is not final, I'm open to suggestions of how to improve it. 
The dropdown item picker is the same one used by the filter functionality in the companies tab.

### CODE REVIEW

**Comment by Stronkness** [comment]
When i test the application with this PR i get the following error:
`Colors.ts:14 Uncaught Error: Cannot find module '../components/AuthContext'
    at webpackMissingModule (Colors.ts:14:1)
    at ./navigation/BottomTabNavigator.tsx (Colors.ts:14:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./navigation/index.tsx (LinkingConfiguration.ts:74:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./App.tsx (bundle.js:18:69)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)'`
    
    Is this intended?

**Comment by S1monG** [comment]
Thats weird it works fine for me. Did you merge main and this branch locally? `components/AuthContext` is the old AuthContext in this branch. Main has a `AuthContextProvider` instead. So maybe it overrides it the wrong way and the imports get messed up

**Comment by Stronkness** [comment]
I see now, that was on me

**Comment by Stronkness** [comment]
Isn't there supposed to be a Volounteer role also?

**Comment by Stronkness** [comment]
Fixed it, the PR looks good now, thank you

**Review by Stronkness — APPROVED** [review]
🍡

**Pull request merged**
